<html>
<head>
<title> Home </title>
<link rel="stylesheet" href="resources/cssfile.css">
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
 <meta charset="UTF-8">
 <style>
        #map {
            margin: auto;
            height: 400px;
            width: 50%;
        }
    </style>
</head>
<body>
	<header> Victoria Coronavirus Testing Information </header>